# Generated by Django 4.2.8 on 2023-12-22 16:52

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20, null=True)),
                ('contact_no', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_and_time', models.DateTimeField(null=True, validators=[booking.models.validate_date_and_time])),
                ('booking_status', models.CharField(choices=[('Booked', 'Booked'), ('Pending', 'Pending'), ('Cancalled', 'Cancalled'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
                'unique_together': {('date_and_time',)},
            },
        ),
    ]
